/*
 * This file was automatically generated by EvoSuite
 * Mon Jun 23 15:25:38 GMT 2025
 */

package org.apache.bookkeeper.net;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.net.UnknownHostException;
import org.apache.bookkeeper.net.BookieId;
import org.apache.bookkeeper.net.BookieSocketAddress;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class BookieSocketAddress_ESTest extends BookieSocketAddress_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      // Undeclared exception!
      try { 
        BookieSocketAddress.resolveLegacyBookieId((BookieId) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.bookkeeper.net.BookieSocketAddress", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      // Undeclared exception!
      try { 
        BookieSocketAddress.isDummyBookieIdForHostname((BookieId) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.bookkeeper.net.BookieSocketAddress", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      // Undeclared exception!
      try { 
        BookieSocketAddress.createDummyBookieIdForHostname(":%p+l|?Zu0|]rBD/");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // BookieId :%p+l|?Zu0|]rBD/:0 is not valid
         //
         verifyException("org.apache.bookkeeper.net.BookieId", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      BookieSocketAddress bookieSocketAddress0 = null;
      try {
        bookieSocketAddress0 = new BookieSocketAddress(" ,iL65", (-106));
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // com/google/common/net/InetAddresses
         //
         verifyException("org.apache.bookkeeper.net.BookieSocketAddress", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      BookieSocketAddress bookieSocketAddress0 = null;
      try {
        bookieSocketAddress0 = new BookieSocketAddress((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.bookkeeper.net.BookieSocketAddress", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      BookieSocketAddress bookieSocketAddress0 = null;
      try {
        bookieSocketAddress0 = new BookieSocketAddress(":0:0:0");
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // com/google/common/net/InetAddresses
         //
         verifyException("org.apache.bookkeeper.net.BookieSocketAddress", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      BookieSocketAddress bookieSocketAddress0 = null;
      try {
        bookieSocketAddress0 = new BookieSocketAddress(":%p+l|?Zu0|]rBD/");
        fail("Expecting exception: UnknownHostException");
      
      } catch(Throwable e) {
         //
         // :%p+l|?Zu0|]rBD/
         //
         verifyException("org.apache.bookkeeper.net.BookieSocketAddress", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      BookieSocketAddress bookieSocketAddress0 = null;
      try {
        bookieSocketAddress0 = new BookieSocketAddress("");
        fail("Expecting exception: UnknownHostException");
      
      } catch(Throwable e) {
         //
         // 
         //
         verifyException("org.apache.bookkeeper.net.BookieSocketAddress", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      BookieId bookieId0 = BookieId.parse("jsJ1p1Ch");
      try { 
        BookieSocketAddress.resolveLegacyBookieId(bookieId0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Cannot resolve bookieId jsJ1p1Ch, bookie does not exist or it is not running
         //
         verifyException("org.apache.bookkeeper.net.BookieSocketAddress", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      BookieId bookieId0 = BookieId.parse(":0:0");
      // Undeclared exception!
      try { 
        BookieSocketAddress.resolveLegacyBookieId(bookieId0);
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // com/google/common/net/InetAddresses
         //
         verifyException("org.apache.bookkeeper.net.BookieSocketAddress", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      BookieId bookieId0 = BookieSocketAddress.createDummyBookieIdForHostname("");
      boolean boolean0 = BookieSocketAddress.isDummyBookieIdForHostname(bookieId0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      BookieId bookieId0 = BookieId.parse("jsJ1p1Ch");
      boolean boolean0 = BookieSocketAddress.isDummyBookieIdForHostname(bookieId0);
      assertFalse(boolean0);
  }
}
