m/*
 * This file was automatically generated by EvoSuite
 * Sun Jun 29 06:44:23 GMT 2025
 */

package org.apache.bookkeeper.bookie.storage.ldb;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import io.netty.buffer.PooledByteBufAllocator;
import org.apache.bookkeeper.bookie.storage.ldb.WriteCache;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class WriteCache_ESTest extends WriteCache_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      int int0 = WriteCache.align64(0);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      int int0 = WriteCache.align64((-465));
      assertEquals((-448), int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      PooledByteBufAllocator pooledByteBufAllocator0 = PooledByteBufAllocator.DEFAULT;
      WriteCache writeCache0 = null;
      try {
        writeCache0 = new WriteCache(pooledByteBufAllocator0, 0L, 9);
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // com/google/common/base/Preconditions
         //
         verifyException("org.apache.bookkeeper.util.collections.ConcurrentLongLongPairHashMap", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      PooledByteBufAllocator pooledByteBufAllocator0 = PooledByteBufAllocator.DEFAULT;
      WriteCache writeCache0 = null;
      try {
        writeCache0 = new WriteCache(pooledByteBufAllocator0, 8L);
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // com/google/common/base/Preconditions
         //
         verifyException("org.apache.bookkeeper.util.collections.ConcurrentLongLongPairHashMap", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      int int0 = WriteCache.align64(4698);
      assertEquals(4736, int0);
  }
}
