name: CI Apache BookKeeper

on:
  push:
    branches:
      - master  # Modificato per usare il branch corretto
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repository
        uses: actions/checkout@v3

      - name: Imposta OpenJDK 17.0.14
        uses: actions/setup-java@v3
        with:
          java-version: '17.0.14'
          distribution: 'temurin'
          cache: 'maven'

      - name: Verifica versione Java
        run: java -version

      - name: Pulizia e Build con Maven
        run: mvn clean install -DskipTests
